package com.nawandarfilmes.Hibernate;
// Generated Oct 8, 2015 3:47:50 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * CashPayment generated by hbm2java
 */
public class CashPayment  implements java.io.Serializable {


     private Integer cashId;
     private WorkOrder workOrder;
     private String depositerName;
     private Double amtRecv;
     private Date amtRecvDate;
     private String amtRecvTime;
     private Boolean recvMg;
     private Boolean recOther;
     private Date entryDateTime;

    public CashPayment() {
    }

    public CashPayment(WorkOrder workOrder, String depositerName, Double amtRecv, Date amtRecvDate, String amtRecvTime, Boolean recvMg, Boolean recOther, Date entryDateTime) {
       this.workOrder = workOrder;
       this.depositerName = depositerName;
       this.amtRecv = amtRecv;
       this.amtRecvDate = amtRecvDate;
       this.amtRecvTime = amtRecvTime;
       this.recvMg = recvMg;
       this.recOther = recOther;
       this.entryDateTime = entryDateTime;
    }
   
    public Integer getCashId() {
        return this.cashId;
    }
    
    public void setCashId(Integer cashId) {
        this.cashId = cashId;
    }
    public WorkOrder getWorkOrder() {
        return this.workOrder;
    }
    
    public void setWorkOrder(WorkOrder workOrder) {
        this.workOrder = workOrder;
    }
    public String getDepositerName() {
        return this.depositerName;
    }
    
    public void setDepositerName(String depositerName) {
        this.depositerName = depositerName;
    }
    public Double getAmtRecv() {
        return this.amtRecv;
    }
    
    public void setAmtRecv(Double amtRecv) {
        this.amtRecv = amtRecv;
    }
    public Date getAmtRecvDate() {
        return this.amtRecvDate;
    }
    
    public void setAmtRecvDate(Date amtRecvDate) {
        this.amtRecvDate = amtRecvDate;
    }
    public String getAmtRecvTime() {
        return this.amtRecvTime;
    }
    
    public void setAmtRecvTime(String amtRecvTime) {
        this.amtRecvTime = amtRecvTime;
    }
    public Boolean getRecvMg() {
        return this.recvMg;
    }
    
    public void setRecvMg(Boolean recvMg) {
        this.recvMg = recvMg;
    }
    public Boolean getRecOther() {
        return this.recOther;
    }
    
    public void setRecOther(Boolean recOther) {
        this.recOther = recOther;
    }
    public Date getEntryDateTime() {
        return this.entryDateTime;
    }
    
    public void setEntryDateTime(Date entryDateTime) {
        this.entryDateTime = entryDateTime;
    }




}


