package com.nawandarfilmes.Hibernate;
// Generated Sep 19, 2015 2:44:42 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * CheaquePayment generated by hbm2java
 */
public class CheaquePayment  implements java.io.Serializable {


     private Integer cheaqueId;
     private WorkOrder workOrder;
     private String cheaqueNo;
     private String bankName;
     private String depositerName;
     private Double amtRecv;
     private Date amtRecvDate;
     private String amtRecvTime;
     private Boolean recvMg;
     private Boolean recOther;
     private Date entryDateTime;

    public CheaquePayment() {
    }

    public CheaquePayment(WorkOrder workOrder, String cheaqueNo, String bankName, String depositerName, Double amtRecv, Date amtRecvDate, String amtRecvTime, Boolean recvMg, Boolean recOther, Date entryDateTime) {
       this.workOrder = workOrder;
       this.cheaqueNo = cheaqueNo;
       this.bankName = bankName;
       this.depositerName = depositerName;
       this.amtRecv = amtRecv;
       this.amtRecvDate = amtRecvDate;
       this.amtRecvTime = amtRecvTime;
       this.recvMg = recvMg;
       this.recOther = recOther;
       this.entryDateTime = entryDateTime;
    }
   
    public Integer getCheaqueId() {
        return this.cheaqueId;
    }
    
    public void setCheaqueId(Integer cheaqueId) {
        this.cheaqueId = cheaqueId;
    }
    public WorkOrder getWorkOrder() {
        return this.workOrder;
    }
    
    public void setWorkOrder(WorkOrder workOrder) {
        this.workOrder = workOrder;
    }
    public String getCheaqueNo() {
        return this.cheaqueNo;
    }
    
    public void setCheaqueNo(String cheaqueNo) {
        this.cheaqueNo = cheaqueNo;
    }
    public String getBankName() {
        return this.bankName;
    }
    
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }
    public String getDepositerName() {
        return this.depositerName;
    }
    
    public void setDepositerName(String depositerName) {
        this.depositerName = depositerName;
    }
    public Double getAmtRecv() {
        return this.amtRecv;
    }
    
    public void setAmtRecv(Double amtRecv) {
        this.amtRecv = amtRecv;
    }
    public Date getAmtRecvDate() {
        return this.amtRecvDate;
    }
    
    public void setAmtRecvDate(Date amtRecvDate) {
        this.amtRecvDate = amtRecvDate;
    }
    public String getAmtRecvTime() {
        return this.amtRecvTime;
    }
    
    public void setAmtRecvTime(String amtRecvTime) {
        this.amtRecvTime = amtRecvTime;
    }
    public Boolean getRecvMg() {
        return this.recvMg;
    }
    
    public void setRecvMg(Boolean recvMg) {
        this.recvMg = recvMg;
    }
    public Boolean getRecOther() {
        return this.recOther;
    }
    
    public void setRecOther(Boolean recOther) {
        this.recOther = recOther;
    }
    public Date getEntryDateTime() {
        return this.entryDateTime;
    }
    
    public void setEntryDateTime(Date entryDateTime) {
        this.entryDateTime = entryDateTime;
    }




}


