package com.nawandarfilmes.Hibernate;
// Generated Oct 8, 2015 3:47:50 PM by Hibernate Tools 3.2.1.GA



/**
 * MembersDetail generated by hbm2java
 */
public class MembersDetail  implements java.io.Serializable {


     private Integer MId;
     private PartyDetail partyDetail;
     private String MName;
     private String MEmail;
     private String MContact;

    public MembersDetail() {
    }

    public MembersDetail(PartyDetail partyDetail, String MName, String MEmail, String MContact) {
       this.partyDetail = partyDetail;
       this.MName = MName;
       this.MEmail = MEmail;
       this.MContact = MContact;
    }
   
    public Integer getMId() {
        return this.MId;
    }
    
    public void setMId(Integer MId) {
        this.MId = MId;
    }
    public PartyDetail getPartyDetail() {
        return this.partyDetail;
    }
    
    public void setPartyDetail(PartyDetail partyDetail) {
        this.partyDetail = partyDetail;
    }
    public String getMName() {
        return this.MName;
    }
    
    public void setMName(String MName) {
        this.MName = MName;
    }
    public String getMEmail() {
        return this.MEmail;
    }
    
    public void setMEmail(String MEmail) {
        this.MEmail = MEmail;
    }
    public String getMContact() {
        return this.MContact;
    }
    
    public void setMContact(String MContact) {
        this.MContact = MContact;
    }




}


