package com.nawandarfilmes.Hibernate;
// Generated Sep 19, 2015 2:44:42 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MovieDetail generated by hbm2java
 */
public class MovieDetail  implements java.io.Serializable {


     private Integer movId;
     private String movName;
     private String movProduces;
     private Date movReleaseDate;
     private String movBannesImgLink;
     private String movYoutubeLink;
     private Set<WorkOrder> workOrders = new HashSet<WorkOrder>(0);

    public MovieDetail() {
    }

    public MovieDetail(String movName, String movProduces, Date movReleaseDate, String movBannesImgLink, String movYoutubeLink, Set<WorkOrder> workOrders) {
       this.movName = movName;
       this.movProduces = movProduces;
       this.movReleaseDate = movReleaseDate;
       this.movBannesImgLink = movBannesImgLink;
       this.movYoutubeLink = movYoutubeLink;
       this.workOrders = workOrders;
    }
   
    public Integer getMovId() {
        return this.movId;
    }
    
    public void setMovId(Integer movId) {
        this.movId = movId;
    }
    public String getMovName() {
        return this.movName;
    }
    
    public void setMovName(String movName) {
        this.movName = movName;
    }
    public String getMovProduces() {
        return this.movProduces;
    }
    
    public void setMovProduces(String movProduces) {
        this.movProduces = movProduces;
    }
    public Date getMovReleaseDate() {
        return this.movReleaseDate;
    }
    
    public void setMovReleaseDate(Date movReleaseDate) {
        this.movReleaseDate = movReleaseDate;
    }
    public String getMovBannesImgLink() {
        return this.movBannesImgLink;
    }
    
    public void setMovBannesImgLink(String movBannesImgLink) {
        this.movBannesImgLink = movBannesImgLink;
    }
    public String getMovYoutubeLink() {
        return this.movYoutubeLink;
    }
    
    public void setMovYoutubeLink(String movYoutubeLink) {
        this.movYoutubeLink = movYoutubeLink;
    }
    public Set<WorkOrder> getWorkOrders() {
        return this.workOrders;
    }
    
    public void setWorkOrders(Set<WorkOrder> workOrders) {
        this.workOrders = workOrders;
    }




}


