package com.nawandarfilmes.Hibernate;
// Generated Sep 19, 2015 2:44:42 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * NeftRtgsPayment generated by hbm2java
 */
public class NeftRtgsPayment  implements java.io.Serializable {


     private Integer nrId;
     private WorkOrder workOrder;
     private String utrNo;
     private String depositerName;
     private Boolean neft;
     private Boolean rtgs;
     private Double amtRecv;
     private Date amtRecvDate;
     private String amtRecvTime;
     private Boolean recvMg;
     private Boolean recOther;
     private Date entryDateTime;

    public NeftRtgsPayment() {
    }

    public NeftRtgsPayment(WorkOrder workOrder, String utrNo, String depositerName, Boolean neft, Boolean rtgs, Double amtRecv, Date amtRecvDate, String amtRecvTime, Boolean recvMg, Boolean recOther, Date entryDateTime) {
       this.workOrder = workOrder;
       this.utrNo = utrNo;
       this.depositerName = depositerName;
       this.neft = neft;
       this.rtgs = rtgs;
       this.amtRecv = amtRecv;
       this.amtRecvDate = amtRecvDate;
       this.amtRecvTime = amtRecvTime;
       this.recvMg = recvMg;
       this.recOther = recOther;
       this.entryDateTime = entryDateTime;
    }
   
    public Integer getNrId() {
        return this.nrId;
    }
    
    public void setNrId(Integer nrId) {
        this.nrId = nrId;
    }
    public WorkOrder getWorkOrder() {
        return this.workOrder;
    }
    
    public void setWorkOrder(WorkOrder workOrder) {
        this.workOrder = workOrder;
    }
    public String getUtrNo() {
        return this.utrNo;
    }
    
    public void setUtrNo(String utrNo) {
        this.utrNo = utrNo;
    }
    public String getDepositerName() {
        return this.depositerName;
    }
    
    public void setDepositerName(String depositerName) {
        this.depositerName = depositerName;
    }
    public Boolean getNeft() {
        return this.neft;
    }
    
    public void setNeft(Boolean neft) {
        this.neft = neft;
    }
    public Boolean getRtgs() {
        return this.rtgs;
    }
    
    public void setRtgs(Boolean rtgs) {
        this.rtgs = rtgs;
    }
    public Double getAmtRecv() {
        return this.amtRecv;
    }
    
    public void setAmtRecv(Double amtRecv) {
        this.amtRecv = amtRecv;
    }
    public Date getAmtRecvDate() {
        return this.amtRecvDate;
    }
    
    public void setAmtRecvDate(Date amtRecvDate) {
        this.amtRecvDate = amtRecvDate;
    }
    public String getAmtRecvTime() {
        return this.amtRecvTime;
    }
    
    public void setAmtRecvTime(String amtRecvTime) {
        this.amtRecvTime = amtRecvTime;
    }
    public Boolean getRecvMg() {
        return this.recvMg;
    }
    
    public void setRecvMg(Boolean recvMg) {
        this.recvMg = recvMg;
    }
    public Boolean getRecOther() {
        return this.recOther;
    }
    
    public void setRecOther(Boolean recOther) {
        this.recOther = recOther;
    }
    public Date getEntryDateTime() {
        return this.entryDateTime;
    }
    
    public void setEntryDateTime(Date entryDateTime) {
        this.entryDateTime = entryDateTime;
    }




}


