package com.nawandarfilmes.Hibernate;
// Generated Sep 19, 2015 2:44:42 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ProfitTicketLog generated by hbm2java
 */
public class ProfitTicketLog  implements java.io.Serializable {


     private Integer ptId;
     private WorkOrder workOrder;
     private Integer ticketSold;
     private Double grossProfit;
     private Double nettProfit;
     private Double edtaxProfit;
     private Date logDate;
     private Date entryDateTime;

    public ProfitTicketLog() {
    }

    public ProfitTicketLog(WorkOrder workOrder, Integer ticketSold, Double grossProfit, Double nettProfit, Double edtaxProfit, Date logDate, Date entryDateTime) {
       this.workOrder = workOrder;
       this.ticketSold = ticketSold;
       this.grossProfit = grossProfit;
       this.nettProfit = nettProfit;
       this.edtaxProfit = edtaxProfit;
       this.logDate = logDate;
       this.entryDateTime = entryDateTime;
    }
   
    public Integer getPtId() {
        return this.ptId;
    }
    
    public void setPtId(Integer ptId) {
        this.ptId = ptId;
    }
    public WorkOrder getWorkOrder() {
        return this.workOrder;
    }
    
    public void setWorkOrder(WorkOrder workOrder) {
        this.workOrder = workOrder;
    }
    public Integer getTicketSold() {
        return this.ticketSold;
    }
    
    public void setTicketSold(Integer ticketSold) {
        this.ticketSold = ticketSold;
    }
    public Double getGrossProfit() {
        return this.grossProfit;
    }
    
    public void setGrossProfit(Double grossProfit) {
        this.grossProfit = grossProfit;
    }
    public Double getNettProfit() {
        return this.nettProfit;
    }
    
    public void setNettProfit(Double nettProfit) {
        this.nettProfit = nettProfit;
    }
    public Double getEdtaxProfit() {
        return this.edtaxProfit;
    }
    
    public void setEdtaxProfit(Double edtaxProfit) {
        this.edtaxProfit = edtaxProfit;
    }
    public Date getLogDate() {
        return this.logDate;
    }
    
    public void setLogDate(Date logDate) {
        this.logDate = logDate;
    }
    public Date getEntryDateTime() {
        return this.entryDateTime;
    }
    
    public void setEntryDateTime(Date entryDateTime) {
        this.entryDateTime = entryDateTime;
    }




}


