package com.nawandarfilmes.Hibernate;
// Generated Oct 8, 2015 3:47:50 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * ScreenDetail generated by hbm2java
 */
public class ScreenDetail  implements java.io.Serializable {


     private Integer SId;
     private TheaterDetail theaterDetail;
     private PartyDetail partyDetail;
     private String SName;
     private Integer SNumber;
     private Integer SSeats;
     private Set<WorkOrder> workOrders = new HashSet<WorkOrder>(0);

    public ScreenDetail() {
    }

    public ScreenDetail(TheaterDetail theaterDetail, PartyDetail partyDetail, String SName, Integer SNumber, Integer SSeats, Set<WorkOrder> workOrders) {
       this.theaterDetail = theaterDetail;
       this.partyDetail = partyDetail;
       this.SName = SName;
       this.SNumber = SNumber;
       this.SSeats = SSeats;
       this.workOrders = workOrders;
    }
   
    public Integer getSId() {
        return this.SId;
    }
    
    public void setSId(Integer SId) {
        this.SId = SId;
    }
    public TheaterDetail getTheaterDetail() {
        return this.theaterDetail;
    }
    
    public void setTheaterDetail(TheaterDetail theaterDetail) {
        this.theaterDetail = theaterDetail;
    }
    public PartyDetail getPartyDetail() {
        return this.partyDetail;
    }
    
    public void setPartyDetail(PartyDetail partyDetail) {
        this.partyDetail = partyDetail;
    }
    public String getSName() {
        return this.SName;
    }
    
    public void setSName(String SName) {
        this.SName = SName;
    }
    public Integer getSNumber() {
        return this.SNumber;
    }
    
    public void setSNumber(Integer SNumber) {
        this.SNumber = SNumber;
    }
    public Integer getSSeats() {
        return this.SSeats;
    }
    
    public void setSSeats(Integer SSeats) {
        this.SSeats = SSeats;
    }
    public Set<WorkOrder> getWorkOrders() {
        return this.workOrders;
    }
    
    public void setWorkOrders(Set<WorkOrder> workOrders) {
        this.workOrders = workOrders;
    }




}


