package com.nawandarfilmes.Hibernate;
// Generated Oct 8, 2015 3:47:50 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * WoAgrrement generated by hbm2java
 */
public class WoAgrrement  implements java.io.Serializable {


     private Integer woAggriId;
     private WorkOrder workOrder;
     private Integer weekNo;
     private Double theaterRent;
     private Double distributerShare;
     private Double ownerShare;
     private Date startDate;
     private Date endDate;
     private Set<ShowCancelLog> showCancelLogs = new HashSet<ShowCancelLog>(0);

    public WoAgrrement() {
    }

    public WoAgrrement(WorkOrder workOrder, Integer weekNo, Double theaterRent, Double distributerShare, Double ownerShare, Date startDate, Date endDate, Set<ShowCancelLog> showCancelLogs) {
       this.workOrder = workOrder;
       this.weekNo = weekNo;
       this.theaterRent = theaterRent;
       this.distributerShare = distributerShare;
       this.ownerShare = ownerShare;
       this.startDate = startDate;
       this.endDate = endDate;
       this.showCancelLogs = showCancelLogs;
    }
   
    public Integer getWoAggriId() {
        return this.woAggriId;
    }
    
    public void setWoAggriId(Integer woAggriId) {
        this.woAggriId = woAggriId;
    }
    public WorkOrder getWorkOrder() {
        return this.workOrder;
    }
    
    public void setWorkOrder(WorkOrder workOrder) {
        this.workOrder = workOrder;
    }
    public Integer getWeekNo() {
        return this.weekNo;
    }
    
    public void setWeekNo(Integer weekNo) {
        this.weekNo = weekNo;
    }
    public Double getTheaterRent() {
        return this.theaterRent;
    }
    
    public void setTheaterRent(Double theaterRent) {
        this.theaterRent = theaterRent;
    }
    public Double getDistributerShare() {
        return this.distributerShare;
    }
    
    public void setDistributerShare(Double distributerShare) {
        this.distributerShare = distributerShare;
    }
    public Double getOwnerShare() {
        return this.ownerShare;
    }
    
    public void setOwnerShare(Double ownerShare) {
        this.ownerShare = ownerShare;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Set<ShowCancelLog> getShowCancelLogs() {
        return this.showCancelLogs;
    }
    
    public void setShowCancelLogs(Set<ShowCancelLog> showCancelLogs) {
        this.showCancelLogs = showCancelLogs;
    }




}


