package com.nawandarfilmes.Hibernate;
// Generated Sep 19, 2015 2:44:42 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * WorkOrder generated by hbm2java
 */
public class WorkOrder  implements java.io.Serializable {


     private Integer woId;
     private MovieDetail movieDetail;
     private TheaterDetail theaterDetail;
     private ScreenDetail screenDetail;
     private PartyDetail partyDetail;
     private Integer woShowsPerDay;
     private String woUnlockKey;
     private Date woStartDate;
     private Date woEndDate;
     private Boolean woMg;
     private Double woMgAmount;
     private Boolean woRent;
     private Boolean woSharing;
     private Boolean woAggrement;
     private Boolean woSentEmail;
     private Date woDateTimeOfAddtion;
     private Set<ProfitTicketLog> profitTicketLogs = new HashSet<ProfitTicketLog>(0);
     private Set<CheaquePayment> cheaquePayments = new HashSet<CheaquePayment>(0);
     private Set<NeftRtgsPayment> neftRtgsPayments = new HashSet<NeftRtgsPayment>(0);
     private Set<CashPayment> cashPayments = new HashSet<CashPayment>(0);
     private Set<WoAgrrement> woAgrrements = new HashSet<WoAgrrement>(0);

    public WorkOrder() {
    }

    public WorkOrder(MovieDetail movieDetail, TheaterDetail theaterDetail, ScreenDetail screenDetail, PartyDetail partyDetail, Integer woShowsPerDay, String woUnlockKey, Date woStartDate, Date woEndDate, Boolean woMg, Double woMgAmount, Boolean woRent, Boolean woSharing, Boolean woAggrement, Boolean woSentEmail, Date woDateTimeOfAddtion, Set<ProfitTicketLog> profitTicketLogs, Set<CheaquePayment> cheaquePayments, Set<NeftRtgsPayment> neftRtgsPayments, Set<CashPayment> cashPayments, Set<WoAgrrement> woAgrrements) {
       this.movieDetail = movieDetail;
       this.theaterDetail = theaterDetail;
       this.screenDetail = screenDetail;
       this.partyDetail = partyDetail;
       this.woShowsPerDay = woShowsPerDay;
       this.woUnlockKey = woUnlockKey;
       this.woStartDate = woStartDate;
       this.woEndDate = woEndDate;
       this.woMg = woMg;
       this.woMgAmount = woMgAmount;
       this.woRent = woRent;
       this.woSharing = woSharing;
       this.woAggrement = woAggrement;
       this.woSentEmail = woSentEmail;
       this.woDateTimeOfAddtion = woDateTimeOfAddtion;
       this.profitTicketLogs = profitTicketLogs;
       this.cheaquePayments = cheaquePayments;
       this.neftRtgsPayments = neftRtgsPayments;
       this.cashPayments = cashPayments;
       this.woAgrrements = woAgrrements;
    }
   
    public Integer getWoId() {
        return this.woId;
    }
    
    public void setWoId(Integer woId) {
        this.woId = woId;
    }
    public MovieDetail getMovieDetail() {
        return this.movieDetail;
    }
    
    public void setMovieDetail(MovieDetail movieDetail) {
        this.movieDetail = movieDetail;
    }
    public TheaterDetail getTheaterDetail() {
        return this.theaterDetail;
    }
    
    public void setTheaterDetail(TheaterDetail theaterDetail) {
        this.theaterDetail = theaterDetail;
    }
    public ScreenDetail getScreenDetail() {
        return this.screenDetail;
    }
    
    public void setScreenDetail(ScreenDetail screenDetail) {
        this.screenDetail = screenDetail;
    }
    public PartyDetail getPartyDetail() {
        return this.partyDetail;
    }
    
    public void setPartyDetail(PartyDetail partyDetail) {
        this.partyDetail = partyDetail;
    }
    public Integer getWoShowsPerDay() {
        return this.woShowsPerDay;
    }
    
    public void setWoShowsPerDay(Integer woShowsPerDay) {
        this.woShowsPerDay = woShowsPerDay;
    }
    public String getWoUnlockKey() {
        return this.woUnlockKey;
    }
    
    public void setWoUnlockKey(String woUnlockKey) {
        this.woUnlockKey = woUnlockKey;
    }
    public Date getWoStartDate() {
        return this.woStartDate;
    }
    
    public void setWoStartDate(Date woStartDate) {
        this.woStartDate = woStartDate;
    }
    public Date getWoEndDate() {
        return this.woEndDate;
    }
    
    public void setWoEndDate(Date woEndDate) {
        this.woEndDate = woEndDate;
    }
    public Boolean getWoMg() {
        return this.woMg;
    }
    
    public void setWoMg(Boolean woMg) {
        this.woMg = woMg;
    }
    public Double getWoMgAmount() {
        return this.woMgAmount;
    }
    
    public void setWoMgAmount(Double woMgAmount) {
        this.woMgAmount = woMgAmount;
    }
    public Boolean getWoRent() {
        return this.woRent;
    }
    
    public void setWoRent(Boolean woRent) {
        this.woRent = woRent;
    }
    public Boolean getWoSharing() {
        return this.woSharing;
    }
    
    public void setWoSharing(Boolean woSharing) {
        this.woSharing = woSharing;
    }
    public Boolean getWoAggrement() {
        return this.woAggrement;
    }
    
    public void setWoAggrement(Boolean woAggrement) {
        this.woAggrement = woAggrement;
    }
    public Boolean getWoSentEmail() {
        return this.woSentEmail;
    }
    
    public void setWoSentEmail(Boolean woSentEmail) {
        this.woSentEmail = woSentEmail;
    }
    public Date getWoDateTimeOfAddtion() {
        return this.woDateTimeOfAddtion;
    }
    
    public void setWoDateTimeOfAddtion(Date woDateTimeOfAddtion) {
        this.woDateTimeOfAddtion = woDateTimeOfAddtion;
    }
    public Set<ProfitTicketLog> getProfitTicketLogs() {
        return this.profitTicketLogs;
    }
    
    public void setProfitTicketLogs(Set<ProfitTicketLog> profitTicketLogs) {
        this.profitTicketLogs = profitTicketLogs;
    }
    public Set<CheaquePayment> getCheaquePayments() {
        return this.cheaquePayments;
    }
    
    public void setCheaquePayments(Set<CheaquePayment> cheaquePayments) {
        this.cheaquePayments = cheaquePayments;
    }
    public Set<NeftRtgsPayment> getNeftRtgsPayments() {
        return this.neftRtgsPayments;
    }
    
    public void setNeftRtgsPayments(Set<NeftRtgsPayment> neftRtgsPayments) {
        this.neftRtgsPayments = neftRtgsPayments;
    }
    public Set<CashPayment> getCashPayments() {
        return this.cashPayments;
    }
    
    public void setCashPayments(Set<CashPayment> cashPayments) {
        this.cashPayments = cashPayments;
    }
    public Set<WoAgrrement> getWoAgrrements() {
        return this.woAgrrements;
    }
    
    public void setWoAgrrements(Set<WoAgrrement> woAgrrements) {
        this.woAgrrements = woAgrrements;
    }




}


